### ISSUE TITLE
Q2 Roadmap

### ISSUE THREAD

**Issue by XiaoningDing** [bd-iaas-us/vllm#2]
The vLLM issues we plan to work on in Q2:
- [ ] QLORA/QA-QLORA: 
     - [x] https://github.com/vllm-project/vllm/pull/4776
     - [x] https://github.com/bd-iaas-us/vllm/issues/12
     - [ ] https://github.com/bd-iaas-us/vllm/issues/13
- [ ] Sparse KV cache
     - [x] issue to doc https://github.com/bd-iaas-us/vllm/issues/5
     - [x] https://github.com/bd-iaas-us/vllm/issues/11
     - [x] https://github.com/vllm-project/vllm/issues/3532
- [ ] CPU offload: 
    - [x] https://github.com/bd-iaas-us/vllm/issues/3 
    - [ ] https://github.com/vllm-project/vllm/issues/3563 (depending on if we find actual scenarios)
- [ ] LongRope: https://github.com/vllm-project/vllm/issues/3575
- [ ] GUFF support: https://github.com/bd-iaas-us/vllm/issues/8
- [ ] Speculative Streaming: https://github.com/vllm-project/vllm/issues/2943
- [ ] H100 support: https://github.com/vllm-project/vllm/issues/2107
- [x] Support NF4 quant model: https://github.com/bd-iaas-us/vllm/issues/14
- [ ] investigate prefill and decoding  desegregation of https://github.com/LLMServe/DistServe
